
mysql> USE pysport;
ERROR 1049 (42000): Unknown database 'pysport'
mysql> USE pysports;
Database changed
mysql> SHOW tables;
+--------------------+
| Tables_in_pysports |
+--------------------+
| player             |
| team               |
+--------------------+
2 rows in set (0.02 sec)

mysql> CREATE TABLE team (
    ->   team_id INT AUTO_INCREMENT PRIMARY KEY,
    ->   team_name VARCHAR(75) NOT NULL,
    ->   mascot VARCHAR(75) NOT NULL
    -> );
ERROR 1050 (42S01): Table 'team' already exists
mysql> SELECT team_id FROM team WHERE team_name = 'Team Sauron';
Empty set (0.00 sec)

mysql> pip install mysql-connector-python
    -> import mysql.connector
    -> from mysql.connector import errorcode
    -> config = {
    ->     "user": "pysports_user",
    ->     "password": "MySQL8IsGreat!",
    ->     "host": "127.0.0.1",
    ->     "raise_on_warnings": True
    -> }
    -> try:
    ->     db = mysql.connector.connect(**config)
    ->     print("\nDatabase user {} connected to MySQL on host {} with database {}".format(config["user"], config["host"], config["database"]))
    ->     input("\n\nPress any key to continue...")
    -> except mysql.connector.Error as error:
    ->     print("The supplied username or password is invalid")
    ->     if error.errno == errorcode.ER_BAD_DBERROR:
    ->         print("The specified database does not exist")
    -> finally:
    ->     db.close()
    -> echo "# module8" >> README.md
    -> git init
    -> git add README.md
    -> git commit -m "first commit"
    -> git branch -M main
    -> git remote add origin https://github.com/yrmxg77/module8.git
    -> git push -u origin main
